src/components/main/process/Process.tsx, src/components/main/process/helpers/helpers.ts, src/components/main/process/helpers/index.ts, src/components/main/process/hooks/index.ts, src/components/main/process/hooks/useAppTitle.ts, src/components/main/process/hooks/useProcessorNodeTree.ts, src/components/main/process/hooks/useProcessorUpdateOpt.ts, src/components/main/process/hooks/useProcessorValidNodeTree.ts, src/components/main/process/hooks/useSaveCommand.ts, src/index.tsx
Process.tsx was refactored by creating helpers functions and hooks.
=> #257 -  Process.tsx (refactor)

src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.tsx
Separating the codeview module business and presentational logic
=> Codeview modularization

src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/createFileOrFolder.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/duplicateNode.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/loadIDBProject.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/loadLocalProject.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/moveActions.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/moveFile.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/processHandlerObj.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/renameNode.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/validateAndDeleteNode.ts, src/components/main/actionsPanel/workspaceTreeView/helpers/validateAndMoveNode.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useFileOperations.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useReloadProject.ts, src/components/main/stageView/iFrame/helpers/cloneAndInsertNode.ts, src/components/main/stageView/iFrame/helpers/createAndInsertElement.ts, src/components/main/stageView/iFrame/hooks/useSideEffectHandlers.ts
1) The 'cut' function has been fixed.
2) After refactoring IFrame.tsx and workspaceTreeView.tsx, numerous warnings and errors appeared due to the incorrect usage of custom hooks. These issues have now been fixed. In the dev branch, errors are appearing after almost every action, and this pull request (PR) aims to address that.
Errors are related to using custom hooks inside functions.
=> Problem fixes

src/_node/html/apis.ts, src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/nodeTreeView/helpers/creatingNode.ts, src/components/main/codeView/hooks/useEditor.tsx, src/components/main/process/helpers/helpers.ts, src/components/main/process/hooks/useProcessorUpdateOpt.ts, src/components/main/stageView/iFrame/IFrame.tsx, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts, src/components/main/stageView/iFrame/hooks/useSetSelectItem.ts, src/components/main/stageView/iFrame/hooks/useTextEditing.ts
Some good code improvement for readability and redundancy removal
=> Code modularizing

src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.tsx, src/components/main/process/helpers/helpers.ts
Fixed similar code highlights in codeview.
[Issue 295](https://github.com/rnbwdev/rnbw/issues/295)
=> #rnbw-295 highlights duplication

src/_node/apis.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts, src/components/main/process/helpers/helpers.ts, src/components/main/process/hooks/useProcessorUpdateOpt.ts
Fixed issue with deleting node 
[Issue 296](https://github.com/orgs/rnbwdev/projects/4/views/5?pane=issue&itemId=40370410)
=> rnbw #296 removing node issue

src/components/main/codeView/hooks/useEditor.tsx
Fixed row changing after Enter click.
Fixed single and multiple line text pasting.
=> rnbw-299 typing issue

package-lock.json, package.json, src/_node/html/apis.ts, src/_node/html/types.ts, src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.tsx
Using dom-diffing to sync codeview
=> #303 improve parser

src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Fixed multiple selection from stage with Shift button.
=> rnbw-316: Multiple selecting from stage

src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Cut-past implemented
To existing copy function added logic to remove attributes from internal elements of the copied element, its done to avoid unnecessary attributes.
=> rnbw-319:  Implementing cut-paste 

src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Implemented nodes duplication.
To achieve the correct duplication of multiple nodes, a sorting array from max endIndex to min endIndex is added to the function, since in each iteration the positions of the selected nodes change (the duplicate node is inserted into the code content), but these changes are not listened to, and thus, if the selected is not sorted node duplicate array nodes are inserted in the wrong place.
=> rnbw-324: Implementing nodes duplication

src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/components/main/actionsPanel/nodeTreeView/helpers/index.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts
Implemented drag and drops, some function that was duplicated added to helpers.
=> rnbw-325: Implementing drag and drop

src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
Implemented group and ungroup nodes using concept describe in [issue 331](https://github.com/rnbwdev/rnbw/issues/331)
=> 331 group and ungroup

src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts, src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.tsx, src/components/main/stageView/iFrame/hooks/useTextEditing.ts
This PR gives following behavior related to focused node.
1. When a node is deleted no node is focused.
2. When a node is added it is focused.
3. Code segment is only focused when cursor position changed on monaco using mouse.
4. Keyboard action is just used for navigating in the code.
=> #311 - Identifying new focused node

src/components/main/stageView/iFrame/hooks/useTextEditing.ts
=> feat: Paste text that is html and turn it into nodes

src/_ref/cmdk.ref/Actions.csv, src/components/main/stageView/iFrame/hooks/useCmdk.ts, src/pages/main/MainPage.tsx, src/types/main.ts
Writing in column Keyboard Shortcut in file Action.csv give opportunity to assign various of shortcuts to one action.
This is achieved by writing shortcuts or keys through a space in the correct place in the table of the .csv file, for example:
Delete,cross,,backspace delete,Basic,"file, html"
=> rnbw-315: Delete action is performed by pressing any of the Delete or Backspace keys

src/pages/main/MainPage.tsx
All options are displayed in the menu.
=> 348 - Fixed options showing

src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
=> rnbw-340: Implemented new node adding

src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts, src/components/main/actionsPanel/navigatorPanel/hooks/useFavicon.ts
Fixed selection first node and expanding tree
=> rnbw-351: Fixed selection first node and expanding tree

src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts, src/components/main/actionsPanel/navigatorPanel/hooks/useFavicon.ts
Fixed selected node updating after typing.
=> rnbw-371: Node updating after typing

src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/pages/main/MainPage.tsx
Fixed adding hovered attribute while grouping.
Fixed actions menu option view.
=> rnbw-368: Hovered attribute while group

src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Commented function that trigger link opening.
=> rnbw-358: Stage link opening

package.json, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActions.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionsHendlers.ts
I tried the native way of formatting the code, but none of the native implementations worked, I read a lot of discussions, but it was not possible to implement it using the native method.
I've explored alternative text formatting techniques and I suggest https://www.npmjs.com/package/js-beautify, a very popular library that has html, css and js formatting features.
This PR is an example of implementation in our application.
=> rnbw-357: Code formatting after actions

src/components/main/codeView/hooks/useEditor.tsx, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Fixed selection from stage.  
[Issue 390](https://github.com/rnbwdev/rnbw/issues/390) 
Part of [Issue 402](https://github.com/rnbwdev/rnbw/issues/402)
=> Fixed selection from stage

src/_node/node/actions.ts, src/_node/node/helpers.ts, src/_node/node/index.ts, src/components/main/processor/hooks/useProcessorValidNodeTree.ts
Fixed wrong place insertion after duplication, past and adding new node.
Fixed loss of focusItem after copy and past action.
Fixed formatting code after past action.
=> rnbw-402: Node action fixes

src/components/main/codeView/CodeView.tsx
Added dependencies for correct hms working.
=> rnbw-427: Fixed code view sync with redo/undo

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx
Fixed expanding while dropping and correct target node selection achieved.
=> 417: Fixed expanding while dropping

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/nodeTreeView/nodeTreeComponents/NodeIcon.tsx
=> Revert "Revert "rnbw-434: Node icon displaying""

src/_ref/cmdk.ref/Actions.csv, src/pages/main/MainPage.tsx, src/pages/main/helper.ts
Added Turn Into UI in cmdk dialog
=> 421: Turn into

src/_ref/cmdk.ref/Jumpstart.csv, src/pages/main/MainPage.tsx
Added autosave toggle to Jumpstart
=> 473: Added autosave to Jumpstart

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/stageView/iFrame/helpers.ts, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts, src/components/main/stageView/iFrame/hooks/useSyncNode.ts
Improved functions with setTimeout using "debounce" to prevent unnecessary function calls.
=> 473: Improved function using debounce

src/components/main/stageView/iFrame/helpers.ts
Converting to node pasted in stage html text.
=> 494: Converting to node pasted html

src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/pages/main/processor/helpers.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts, src/pages/main/processor/hooks/useSaveCommand.ts
=> 497: Fixed mark changed files

src/_node/file/apis.ts, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/helpers/createDefaultFile.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useDefaultFile.tsx
If a folder is empty, a default file will be created. Similarly, if all files are deleted from an existing folder, a default file will be created to prevent the folder from remaining empty.
=> Added default file if folder empty

src/components/main/actionsPanel/workspaceTreeView/hooks/useDefaultFile.tsx
Adding default file if `initialFileUidToOpen` not exist
=> 274 default file

src/pages/main/MainPage.tsx
=> 275: local file sync

src/pages/main/hooks/useHandlers.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
Fixed syncing with `stageView` and `codeView`.
Fixed current file updates after local updates.
=> content updates logic

src/pages/main/MainPage.tsx
This PR was created because the codeview was losing content if we changed the visibility and the visibilitychange handler was executed.
Now we check if current file without changes and anly after that runs reload current project, to get changed local file data
=> fixed losing unsaved content in current file

src/components/main/stageView/iFrame/hooks/useCmdk.ts
=> Add show/hide actions panel and code view

src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/codeView/hooks/useEditor.ts, src/constants/main.ts, src/pages/main/MainPage.tsx, src/pages/main/processor/hooks/useHms.ts, src/pages/main/processor/hooks/useSaveCommand.ts
Added autoSave functionality:
- save on change currentFile;
- save on switching focus away from the app;
- save after Delay;
- delayed save after undo/redo.
=> 555-autoSave

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/stageView/iFrame/IFrame.tsx, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts, src/pages/main/helper.ts
- The Web Component opening code is now corrected to match the current file system code implementation
- The code is also modularised
- Web Component file opens on Dobule Clicking on :
- web component node on the node tree
- web component node on stage
=> Web Component File Open on Doble Click

src/_redux/main/processor/slice.ts, src/_redux/main/processor/types.ts, src/_redux/useAppState.tsx, src/components/common/loader/Loader.tsx, src/components/common/loader/index.ts, src/components/common/loader/types.ts, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/pages/main/MainPage.tsx, src/pages/main/hooks/useHandlers.ts, src/pages/main/processor/hooks/useSaveCommand.ts
Progress bar has been added to project loading, page changing and saving changes.
=> 551 progress bar

src/_redux/main/stageView/slice.ts, src/_redux/main/stageView/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/hooks/useCmdk.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/pages/main/MainPage.tsx, src/pages/main/helper.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
=> Web Component code preview

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/codeView/CodeView.tsx
Fixed scroll to the position from codeView
=> fixed scroll issue

src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/pages/main/MainPage.tsx, src/pages/main/hooks/useInit.ts
Fixed functionality and on reload URL
=> Added correct url

src/_node/node/actions.ts, src/_node/node/helpers.ts, src/_redux/main/nodeTree/slice.ts, src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts, src/components/main/actionsPanel/nodeTreeView/nodeTreeComponents/DragBetweenLine.tsx, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeViewState.ts, src/constants/main.ts
- deleted drag icon 
- highlighting target parent node like in figma
- move like in figma
- selection and move functionality fixes
=> 549 dnd optimization

src/components/main/stageView/StageView.tsx, src/components/main/stageView/iFrame/IFrame.tsx, src/components/main/stageView/iFrame/hooks/useZoom.tsx
Added stage zoom in out, by **number**, **+**, **-** keys
=> stage zoom

src/_redux/main/stageView/slice.ts, src/_redux/main/stageView/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/stageView/iFrame/hooks/useZoom.tsx, src/pages/main/ResizablePanels.tsx, src/pages/main/processor/hooks/useNodeTreeEvent.ts, src/pages/main/types.ts, src/rnbw.css
- fixed codeView position
- showing actionPanel on left side hover
=> Resizable panels

src/components/main/actionsPanel/navigatorPanel/NavigatorPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/DefaultPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/PanelButton.tsx, src/rnbw.css
=> added panel button

src/_node/file/handlers/handlers.ts, src/_node/types.ts, src/_redux/main/stageView/slice.ts, src/_redux/main/stageView/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/components/main/stageView/iFrame/helpers.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
Fixed position losing after content editable
=> fixed position after content editable changes

package-lock.json, package.json, src/_redux/_root/rootSaga.ts, src/_redux/_root/store.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useDefaultFile.tsx, src/pages/main/hooks/useHandlers.ts
Fixed crashing on opening a folder for a very first time
Fixed default html file
Deleted redux saga
=> 621 crash issue

src/components/main/codeView/CodeView.tsx, src/pages/main/ResizablePanels.tsx
Fixed Monaco Editor Model is undefined error
=> 628 code view

src/pages/main/ResizablePanels.tsx
=> Fixed resize behavior

src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/nodeTreeView/nodeTreeComponents/ItemTitle.tsx, src/rnbw.css
=> Sidebar feebacks

src/pages/main/processor/hooks/useNodeTreeEvent.ts
Fixed defocusing after editing from stage.
=> 588: Fixed defocus after editing contenteditable

src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/codeView/CodeView.tsx, src/pages/main/MainPage.tsx
Fixes point 4 in [627](https://github.com/rnbwdev/rnbw/issues/627)
=> fixed radius and borders

src/_node/file/handlers/handlers.ts, src/_node/types.ts, src/_redux/main/nodeTree/slice.ts, src/_redux/main/nodeTree/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
Fixed Collapse bug when drag & drop.
Issue number : #601
=> Fixed Collapse Issue #601

src/_redux/main/nodeTree/event/slice.ts, src/pages/main/hooks/useCmdk.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
=> fix: defocus issue after editing text

src/_node/file/handlers/constants.ts, src/_node/file/handlers/handlers.ts, src/_node/node/actions.ts, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/actionsPanel/navigatorPanel/NavigatorPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/DefaultPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/PanelButton.tsx, src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/settingsPanel/SettingsPanel.tsx, src/components/main/actionsPanel/settingsPanel/index.ts, src/components/main/actionsPanel/settingsPanel/types.ts, src/components/main/actionsPanel/settingsView/SettingsForm.tsx, src/components/main/actionsPanel/settingsView/SettingsView.tsx, src/components/main/actionsPanel/settingsView/hooks/useAttributeHandler.ts, src/components/main/stageView/iFrame/hooks/useZoom.tsx, src/pages/main/hooks/useCmdk.ts, src/rnbw.css
- Added settings panel
- All the attributes of the selected node are displayed
- Ability edit existing attributes (onEnter or onBlur)
- Adding new attribute (on Enter or onBlur)
- Deleting attributes
=> 634 settings

src/_node/file/handlers/handlers.ts, src/_node/types.ts, src/_redux/main/nodeTree/slice.ts, src/_redux/main/nodeTree/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeTreeCallback.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
Reverted PR #647. Collapse Issue.(2hrs)
=> revert: collapse-issue

src/pages/main/ResizablePanels.tsx, src/rnbw.css
- Fixed sidebar issue after Escape
- Fixed resize panel issue
- Fixed types
=> Sidebar issues fixes

src/_node/file/nohostApis.ts, src/pages/main/hooks/useHandlers.ts
Fixed: Current Background File Sync.
=> Filesync issue

src/_node/file/apis.ts, src/_node/file/handlers/handlers.ts, src/_node/node/type/html.ts, src/_redux/main/cmdk/slice.ts, src/_redux/main/codeView/slice.ts, src/_redux/main/codeView/types.ts, src/_redux/main/slice.ts, src/_redux/useAppState.tsx, src/components/main/codeView/CodeView.tsx, src/pages/main/processor/hooks/useNodeTreeEvent.ts
Outlined codeView in case of errors in the code while parsing or morphing.
=> Errors in code

src/_redux/main/processor/slice.ts, src/_redux/main/processor/types.ts, src/_redux/useAppState.tsx, src/components/common/treeComponents/TreeItem.tsx, src/components/common/treeComponents/types.ts, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/actionsPanel/navigatorPanel/NavigatorPanel.tsx, src/components/main/actionsPanel/navigatorPanel/hooks/useNavigatorPanelHandlers.ts, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/workspaceComponents/NodeIcon.tsx, src/rnbw.css
Added vertical resizing
Fixed FilePanel automatically close when focusing on other part of the ui
=> added vertical resizing file panel

package-lock.json, package.json, src/_redux/main/slice.ts, src/index.tsx
2 hours: implement persist redux.
2 hours: filtered only autosave and format code to optimize the local storage test.
=> feat: persist redux with autosave and format code

src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/components/main/actionsPanel/nodeTreeView/hooks/useNodeActionHandlers.ts, src/pages/main/helper.ts
=> added validation on DnD

src/_node/node/actions.ts
=> fixed comment adding

package-lock.json, package.json, src/_node/file/nohostApis.ts, src/app/App.tsx, src/index.html, webpack.config.js
1 hour: upgrade filer cdn to package
=> upgrade: filer cdn to pkg

src/components/main/stageView/iFrame/helpers.ts, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
Fixed attributes leak.
Fixed functionality that allowed to select which element can be editable.
Elements that have child web-components cannot be editable.
=> Fixed attributes leak

src/pages/main/hooks/useCmdkReferenceData.ts, src/pages/main/hooks/useHandlers.ts
Fixed file options in add menu
=> 668 add menu file

src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.ts
=> fixed: morphdom speed

src/components/main/actionsPanel/ActionsPanel.tsx, src/pages/main/MainPage.tsx
=> Vertical panel feedback

src/_node/node/actions.ts, src/components/main/codeView/CodeView.tsx, src/components/main/codeView/hooks/useEditor.ts, src/components/main/stageView/iFrame/helpers.ts
2 hours: catch the events when the focus changed after escape pressed.
1 hour: fixed the focus changing bug
1 hour: testing & while testing the content value user is currently editing, not saved correctly after escape pressed.
5 hours: researching the entire logic and tried to find the reason why the content is changing after escape pressed.
( the final reason was dataSourceLocation problem, dataSourceLocation not updated after edition)
3 hours: fixed the bug by recalculating dataSourceLocation one by one.
=> Escape issue

src/_node/node/actions.ts, src/components/main/actionsPanel/settingsPanel/SettingsPanel.tsx, src/components/main/actionsPanel/settingsPanel/types.ts, src/components/main/actionsPanel/settingsView/SettingsForm.tsx, src/components/main/actionsPanel/settingsView/SettingsView.tsx, src/components/main/actionsPanel/settingsView/hooks/useAttributeHandler.ts, src/rnbw.css
Added handler mechanism for multiple node selection attr
Added design fixes (showing + on hover, toggle and remove logic)
Added hover and editing behavior
Added avoiding keyboard shortcuts while editing
=> Elements settings design

src/components/main/actionsPanel/navigatorPanel/components/PanelButton.tsx, src/pages/main/hooks/useCmdk.ts
- Fixed save redo issue;
- File HMS on opened `FilePanel` and `ActionsPanel`
=> fixed save redo issue and hms flow on closed active panel

package-lock.json, src/components/main/codeView/hooks/useEditor.ts
fix: unable to do code selection when dragging the cursor from bottom to top in codeview
=> Selection issue fix

src/_node/file/handlers/handlers.ts, src/components/main/actionsPanel/nodeTreeView/helpers/helpers.ts, src/components/main/stageView/iFrame/IFrame.tsx, src/pages/main/processor/helpers.ts
- showing #text node only when an element got other element as its children together with #text node;
- improved validations to include operations on #text node copy, paste, DnD, etc.
=> Single or multi level navigation fixes

src/_node/node/actions.ts, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/actionsPanel/settingsPanel/SettingsPanel.tsx, src/components/main/actionsPanel/settingsPanel/types.ts, src/components/main/actionsPanel/settingsView/SettingsForm.tsx, src/components/main/actionsPanel/settingsView/SettingsView.tsx, src/components/main/actionsPanel/settingsView/hooks/useAttributeHandler.ts
Hided settings panel when multiple nodes are selected and deleted unnecessary logic
=> hided settings panel on node multiple selection

src/components/main/stageView/iFrame/IFrame.tsx, src/components/main/stageView/iFrame/hooks/useCmdk.ts, src/components/main/stageView/iFrame/hooks/useMouseEvents.ts
When toggle hover on node using cmd/ctrl the focus on node works without changing the cursor position again
=> 747 keybord focuse issue

src/_node/file/FileSystemApis.ts, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/pages/main/hooks/useHandlers.ts
fixed issue with wrong files opening after background;
fixed issue after deleting file when clicking on stage opens index.html and shows wrong url
=> fixed background sync issue

src/_redux/main/processor/slice.ts, src/pages/main/processor/hooks/useSaveCommand.ts
- was set autosave by default [issue 777](https://github.com/rnbwdev/rnbw/issues/777);
- deleted loader on save [issue 778](https://github.com/rnbwdev/rnbw/issues/778);
=> 777 autosave

src/_node/node/actions.ts, src/components/main/stageView/iFrame/helpers.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
- fixed the unexpected behavior of the node with the id attribute;
- fixed detection double and single quotes on attribute actions;
=> 781 attribute issue

package-lock.json, package.json, src/index.tsx
=> updated @rnbws/renecss

src/_redux/main/fileTree/slice.ts, src/_redux/main/nodeTree/event/slice.ts, src/_redux/main/nodeTree/event/types.ts, src/_redux/useAppState.tsx, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/actionsPanel/navigatorPanel/helpers/helpers.ts, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/components/main/codeView/CodeView.tsx, src/components/main/stageView/iFrame/hooks/useMouseEvents.tsx, src/pages/main/helper.ts, src/pages/main/hooks/useCmdk.ts, src/pages/main/hooks/useHandlers.ts, src/pages/main/processor/hooks/useNodeTreeEvent.ts
- The SettingPanel and the ActionPanel are displayed simultaneously.
- The CodeView is displayed when a file without a design is opened.
- Switching back to "design" is seamless.
- Improved logic for selecting Web Component.
- The Web Component file is displayed when Web Component is selected and double-clicked.
=> Issue 735: Design core interactions

src/components/main/stageView/iFrame/hooks/useMouseEvents.tsx
#text has the behaviour of usual elements
=> #text element issue

README.md
Added Bundle and Release section
=> Issue 764: Bundle and Release section

src/_node/file/apis.ts, src/_node/file/nohostApis.ts, src/pages/main/processor/hooks/useSaveCommand.ts
Fixed `Not Found` error on very first project load.
=> Issue 806: Fixed not found error on very first project load

src/actions/useTurnInto.actions.tsx
Fixed: Multiple Turn into action
=> Fixed turn into issue

src/pages/main/MainPage.tsx, src/pages/main/cmdkPage/CommandDialog.tsx, src/pages/main/cmdkPage/types.ts
Fixed command actions running twice
=> Fixed command actions running twice 

src/pages/main/hooks/useHandlers.ts
Fixed adding default html code in not .html files
=> Fixed adding default html code in not .html files

src/_node/file/apis.ts, src/_node/file/nohostApis.ts, src/services/useFiles.tsx
Deleting issue if the folder is not empty.
=> Deleting issue if the folder is not empty

src/_redux/main/context.ts, src/_redux/main/types.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useNodeActionsHandler.ts, src/components/main/actionsPanel/workspaceTreeView/hooks/useWorkspaceInit.ts, src/components/main/codeView/hooks/useEditor.ts, src/pages/main/MainPage.tsx, src/pages/main/hooks/useHandlers.ts, src/services/useElements.tsx
=> fix: incorrect syncing

src/actions/useFormatCode.action.tsx, src/actions/useTurnInto.actions.tsx, src/components/main/actionsPanel/settingsView/SettingsForm.tsx, src/components/main/actionsPanel/settingsView/SettingsView.tsx, src/services/useElements.tsx, src/services/useElementsHelper.tsx
=> Validation to elements update settings.

src/components/main/stageView/iFrame/hooks/useMouseEvents.tsx, src/services/useElements.tsx, src/services/useElementsHelper.tsx
Fixed node redo and undo behavior
=> Node history fix

src/_node/file/FileSystemApis.ts, src/services/useFiles.tsx
=> idb file actions fixes

src/components/common/treeView/TreeView.tsx, src/components/main/stageView/iFrame/hooks/useCmdk.ts, src/pages/main/hooks/useCmdk.ts
=> fix: rnbw crashing on aborting renaming

src/components/common/notification/Notification.tsx, src/pages/main/processor/hooks/useNodeTreeEvent.ts
the dynamically created JS elements like in rnbw design there is aside. Tt used to get removed by morphdom whenever we made any changes, because we handled the cases for web-component  but no this.
=> Preserve js added html

src/actions/useTurnInto.actions.tsx, src/services/useElements.tsx, src/services/useElementsHelper.tsx
Validation on node add, paste, move, group and turn into.
=> Pasting validation

src/components/canvas/PanAndPinch.tsx, src/components/canvas/Resize.tsx, src/components/common/treeComponents/TreeItem.tsx, src/components/main/actionsPanel/ActionsPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/AdditionalPanel.tsx, src/components/main/actionsPanel/navigatorPanel/components/PanelButton.tsx, src/components/main/actionsPanel/nodeTreeView/NodeTreeView.tsx, src/components/main/actionsPanel/nodeTreeView/nodeTreeComponents/DragBetweenLine.tsx, src/components/main/actionsPanel/settingsPanel/SettingsPanel.tsx, src/components/main/actionsPanel/settingsView/SettingsForm.tsx, src/components/main/actionsPanel/settingsView/SettingsView.tsx, src/components/main/actionsPanel/workspaceTreeView/WorkspaceTreeView.tsx, src/components/main/actionsPanel/workspaceTreeView/hooks/useSync.ts, src/components/main/codeView/CodeView.tsx, src/pages/main/ResizablePanels.tsx, src/pages/main/cmdkPage/CommandDialog.tsx, src/rnbw.css
Hi! I've done the initial cleaning of the classes, please take a look. Also, I'd like to discuss with you which of the remaining classes we should add to rene.css and which ones we should keep in rnbw.css. Here's a list of deleted and retained classes for your convenience: 
body,
#CodeView *:hover,
#iframeId *:hover {
cursor: default !important;
}
#root #NodeTreeView::-webkit-scrollbar {
display: none; /* Chrome, Safari, Opera */
}
#root #NodeTreeView ul,
#root #FileTreeView ul,
#root #SettingsView ul {
padding: 0px;
list-style-type: none;
}
.icon-button {
visibility: visible;
padding: 4px;
display: flex;
justify-content: center;
align-items: center;
}
/* cmdk modal */
[cmdk-overlay] {
position: fixed;
inset: 0;
background: rgba(0, 0, 0, 0.2);
}
[cmdk-dialog] {
position: fixed;
top: 50vh; …
=> Removed unnecessary classes
